### ISSUE TITLE
shim server down?

### ISSUE THREAD

**Issue by feluxe** [heroku/cnb-shim#12]
Hi there,

our build pipeline failed with:

```
ERROR: downloading buildpack from https://cnb-shim.herokuapp.com/v1/heroku-community/apt: could not download from https://cnb-shim.herokuapp.com/v1/heroku-community/apt, code http status 500
##[error]Process completed with exit code 1.
```

I cannot reach these:

https://cnb-shim.herokuapp.com/v1/heroku-community/apt
https://cnb-shim.herokuapp.com/v1/hashnuke/elixir

Both return an "Internal Server Error".

Is the shim-server down?

**Comment by jkutner** [comment]
@feluxe thanks for reporting this. I think you'll find it's working now, but please let us know if it is not.

The root cause was an infrastructure issue.

**Comment by feluxe** [comment]
@jkutner It works. Thanks a lot for the quick response! :-)
