### ISSUE TITLE
v0.3 release

### ISSUE THREAD

**Issue by kamaln7** [heroku/cnb-shim#20]
There have been quite a few changes made since the v0.2 release. Would you be able to look into the possibility of cutting a v0.3 release? Thanks! 😄

**Comment by jabrown85** [comment]
Hey @kamaln7 - I just cut a [new release](https://github.com/heroku/cnb-shim/releases/tag/v0.3). Please check it out and if you run into problems, please open an issue!

**Comment by kamaln7** [comment]
Amazing! I appreciate the quick response @jabrown85
